#!/bin/bash
#PBS -l select=1:ncpus=16
#PBS -l walltime=5000:00:00
#PBS -N F4.SBE3_v1_2sp.r1
#PBS -j oe
#PBS -m ae
#PBS -M seeholzer.glenn@gmail.com
#PBS -o F4.SBE3_v1_2sp.r1.out

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

date
time


rm -rf ./F4.SBE3_v1_2sp.r1
mkdir ./F4.SBE3_v1_2sp.r1

time beast -threads 16 F4.SBE3_v1_2sp.r1.xml


