#!/bin/bash
#PBS -l select=1:ncpus=8
#PBS -l walltime=5000:00:00
#PBS -N F2.SBE3_v3_2sp.r3
#PBS -j oe
#PBS -m ae
#PBS -M seeholzer.glenn@gmail.com
#PBS -o F2.SBE3_v3_2sp.r3.out

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

date
time


rm -rf ./F2.SBE3_v3_2sp.r3
mkdir ./F2.SBE3_v3_2sp.r3

time beast -threads 8 F2.SBE3_v3_2sp.r3.xml


