#!/bin/bash
#PBS -l select=1:ncpus=16
#PBS -l walltime=5000:00:00
#PBS -N F3.SBE3_v3_1sp.r2
#PBS -j oe
#PBS -m ae
#PBS -M seeholzer.glenn@gmail.com
#PBS -o F3.SBE3_v3_1sp.r2.out

# change to the working directory
cd $PBS_O_WORKDIR
echo "pbsworkdir"
echo $PBS_O_WORKDIR
EXECDIR=`pwd`
export PATH=./:$PATH
echo $PATH

date
time


rm -rf ./F3.SBE3_v3_1sp.r2
mkdir ./F3.SBE3_v3_1sp.r2

time beast -threads 16 F3.SBE3_v3_1sp.r2.xml


